---
title: "Prediction & Recommendation"
author: "Mohammed Amir"
date: "April 7, 2017"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(class)
library(caret)
```


```{r}
Dinesafe = read.csv("D:/CAPSTONE/CAPSTONE/DATASET/Final_DineSafe.csv", na.strings='NULL')


```

```{r}
## select a subset of dataset
Dinesafe1 <- unique(Dinesafe[c(2,5:7)])

## Select unique rows
Dinesafe2 <-  unique(Dinesafe1)

nrow(Dinesafe2)

```

```{r}
## Index the cuisine Type label
CUISINE_IDX <- function(CUISINE)
{
  if(CUISINE == "African")
  {
    print ("1")
  }
  else
  {
    if(CUISINE == "Bakeries")
    {
      print ("2")  
    }
    else
    {
      if(CUISINE == "Bar")
      {
        print ("3")  
      }
      else
      {
        if(CUISINE == "Cafe")
        {
          print ("4")  
        }
        else
        {
          if(CUISINE == "Caribbean")
          {
            print ("5")  
          }
          else
          {
            if(CUISINE == "Deli")
            {
              print ("6")  
            }
            else
            {
              if(CUISINE == "Dessert")
              {
                print ("7")  
              }
              else
              {
                if(CUISINE == "European")
                {
                  print ("8")  
                }
                else
                {
                  if(CUISINE == "Far Eastern")
                  {
                    print ("9")  
                  }
                  else
                  {
                    if(CUISINE == "Mediterranean")
                    {
                      print ("10")  
                    }
                    else
                    {
                      if(CUISINE == "Middle Eastern")
                      {
                        print ("11")  
                      }
                      else
                      {
                        if(CUISINE == "North American")
                        {
                          print ("12")  
                        }
                        else
                        {
                          if(CUISINE == "Juicery")
                          {
                            print ("13")  
                          }
                          else
                          {
                            if(CUISINE == "Pastries")
                            {
                              print ("14")  
                            }
                            else
                            {
                              if(CUISINE == "South Asian")
                              {
                                print ("15")  
                              }
                              else
                              {
                                if(CUISINE == "South East Asian")
                                {
                                  print ("16")  
                                }
                                else
                                {
                                  if(CUISINE == "Latin American")
                                  {
                                    print ("17")  
                                  }
                                  else
                                  {
                                    print ("0")
                                  }
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
      
    }
  }
}

## Apply the Index function to cuisine type column
Dinesafe2$CUISINE_IDX <- mapply(CUISINE_IDX,Dinesafe2$CUISINE_TYPE)

```


```{r}
Dinesafe2$African <- ifelse(Dinesafe2$CUISINE_TYPE == "African",1,0)
Dinesafe2$Bakeries <- ifelse(Dinesafe2$CUISINE_TYPE == "Bakeries",1,0)
Dinesafe2$Bar <- ifelse(Dinesafe2$CUISINE_TYPE == "Bar",1,0)
Dinesafe2$Cafe <- ifelse(Dinesafe2$CUISINE_TYPE == "Cafe",1,0)
Dinesafe2$Caribbean <- ifelse(Dinesafe2$CUISINE_TYPE == "Caribbean",1,0)
Dinesafe2$Deli <- ifelse(Dinesafe2$CUISINE_TYPE == "Deli",1,0)
Dinesafe2$Dessert <- ifelse(Dinesafe2$CUISINE_TYPE == "Dessert",1,0)
Dinesafe2$European <- ifelse(Dinesafe2$CUISINE_TYPE == "European",1,0)
Dinesafe2$FarEastern <- ifelse(Dinesafe2$CUISINE_TYPE == "Far Eastern",1,0)
Dinesafe2$Mediterranean <- ifelse(Dinesafe2$CUISINE_TYPE == "Mediterranean",1,0)
Dinesafe2$MidEastern <- ifelse(Dinesafe2$CUISINE_TYPE == "Middle Eastern",1,0)
Dinesafe2$NAmerican <- ifelse(Dinesafe2$CUISINE_TYPE == "North American",1,0)
Dinesafe2$Juicery <- ifelse(Dinesafe2$CUISINE_TYPE == "Juicery",1,0)
Dinesafe2$Pastries <- ifelse(Dinesafe2$CUISINE_TYPE == "Pastries",1,0)
Dinesafe2$SouthAsian <- ifelse(Dinesafe2$CUISINE_TYPE == "South Asian",1,0)
Dinesafe2$SEastAsian <- ifelse(Dinesafe2$CUISINE_TYPE == "South East Asian",1,0)
Dinesafe2$LAmerican <- ifelse(Dinesafe2$CUISINE_TYPE == "Latin American",1,0)



```


```{r}

str(Dinesafe2)
head(Dinesafe2)
```


```{r}
#Dinesafe3 <- subset( Dinesafe2, select = -c( 1 ))
#Dinesafe3
#str(Dinesafe3)

Dinesafe2$CUISINE_IDX <- as.numeric(Dinesafe2$CUISINE_IDX)
str(Dinesafe2)

```

```{r}

#Normalize the dataset feature
normalize <- function(x)
{
num <- x - min(x)
denom <- max(x) - min(x)
return (num/denom)
}

```


```{r}
#Apply normalizeto dataset feature
Norm_RATING <- as.data.frame(lapply(Dinesafe2[,c(2,3,5)], normalize))
str(Norm_RATING)

```



```{r}

#str(Norm_Dinesafe1)
Norm_Dinesafe <- subset( Dinesafe2, select = -c( 2,3,5 ))
#str(Norm_Dinesafe)


Norm_Dinesafe5 <- cbind.data.frame(Norm_Dinesafe, Norm_RATING)

```


```{r}

Norm_Dinesafe6 <- subset( Norm_Dinesafe5, select = -c( 1,2 ))

str(Norm_Dinesafe6)

head(Norm_Dinesafe6)



```


```{r}
nrow(Norm_Dinesafe5)
nrow(Norm_Dinesafe6)

#set.seed(9850)
#gp <- runif(nrow(Norm_Dinesafe6))
#Dinesafe4 <- Norm_Dinesafe6[order(gp),]
#head(Dinesafe4)
```


```{r}
## create a feature
Dine_train <- Norm_Dinesafe6[1:2000,]
Dine_test <- Norm_Dinesafe6[2001:2723,]
nrow(Dine_train)
nrow(Dine_test)

```


```{r}


Dine_trainLabel <- Dinesafe2[1:2000,4]
Dine_testLabel <- Dinesafe2[2001:2723,4]

NROW(Dine_trainLabel)
NROW(Dine_testLabel)

```

```{r , results='hide'}
# Determine best K value in KNN Crosss Validation
set.seed(3333)
trctrl <- trainControl(method = "repeatedcv", number = 10, repeats = 3)


knn_fit <- train(CUISINE_IDX~., data = Dine_train, method = "knn", trControl=trctrl, preProcess = c("center", "scale"),tuneLength = 10)
knn_fit
plot(knn_fit)

```


```{r}
sqrt(2723)
model <- knn(train = Dine_train, test = Dine_test, cl = Dine_trainLabel, k = 5)
model
table (Dine_testLabel, model)

```


```{r}
## Accurry where predicted value is not equal to given label
sum(model != Dine_testLabel)


```



```{r}

confusion <- confusionMatrix(model, Dine_testLabel )
plot <- ggplot(as.data.frame(as.table(confusion)))
```


```{r}
# Put `iris.testLabels` in a data frame
DineTestLabels <- data.frame(Dine_testLabel)

# Merge `iris_pred` and `iris.testLabels` 
merge <- data.frame(model, Dine_testLabel)

# Specify column names for `merge`
names(merge) <- c("Predicted Cuisine", "Observed Cuisine")

# Inspect `merge` 
head(merge,10)
```


```{r}
## RECOMMENDATION 

library(class)
library(caret)
#library(lattice)
#library(ggplot2)

#load dataset
recommender  <- Dine_test


```

```{r}
## Create a matrix using euclidean distance 
distances <- as.matrix(dist(recommender , method="euclidean")) 

```


```{r}
## Computes the nearest neighbors for i
k.nearest.neighbors <- function(i, recommender, k = 5)
{
  ordered.neighbors <- order(recommender[i, ])
  return(ordered.neighbors[2:(k + 1)])
}
```


```{r}
## calculate probability of the closest restaurant 
seen.probability <- function(cuisine, restaurant, recommender, distances, k = 25)
{
  neighbors <- k.nearest.neighbors(which(row.names(recommender) == restaurant), distances, k)
  return(mean(recommender[neighbors, cuisine]))
}

```

```{r}
## Predict a recommendation based on cuisine input, recommender matrix, distance between restaurants and K value 
most.probable.recommend <- function(cuisine, recommender, distances, k = 25)
{
  probabilities <- rep(0, nrow(recommender))
  for (i in 1:nrow(recommender)) { # For each restaurant
    if (recommender[i,cuisine] == 1) {
      next 
    }
    probabilities[i] <- seen.probability(cuisine, row.names(recommender)[i], recommender, distances, k)
  }
  return(order(probabilities, decreasing=T))
}
```

```{r}
cuisine <- "African"
listing <- most.probable.recommend(cuisine, recommender, distances)
rownames(recommender)[listing[1:3]]
```


Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
